# Generated by Django 5.1.1 on 2024-10-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Facial Treatment', 'Facial Treatment'), ('Haircut', 'Haircut'), ('Massage', 'Massage'), ('Nails', 'Nails'), ('Makeup', 'Makeup'), ('Waxing', 'Waxing')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
