# Generated by Django 5.1.1 on 2024-10-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_offer_alter_appointment_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
