# Generated by Django 5.1.1 on 2024-10-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_offer_end_date_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
    ]
