# Generated by Django 5.1.1 on 2024-10-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
    ]
