# Generated by Django 5.1.1 on 2024-10-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_remove_offer_end_date_remove_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
